### PR TITLE
Features

### PR DESCRIPTION
**Pull request by sebas095**
@pin3da

### CODE REVIEW

**Comment by leiverandres** [comment]
I doesn't work fully yet ...

**Comment by sebas095** [comment]
Today I check it and  correcta it

**Comment by pin3da** [comment]
Hi, 

first of all thanks for your work, is really appreciated.

I try to start the project and it does not work, the browser/main file has problems with the opening/closing brackets, it also includes files that are not in the repo.

After that i tried to understand the code and I found several inconsistencies. 

- why you created json files to populate the data ? the backend currently supports several methods to create and query resources, use them.
- You are applying css directly into the components (for example, <div className="col-4">) I'm not sure if this is the right way. CC @caal-15 
- I see several commits doing the same thing, it is not a big problem, but would be better if we maintain the git history as clear as possible, [recommendation here](https://medium.com/@tjholowaychuk/git-conventions-a940ee20862d#.ovvbqspya)
- You are adding some commented code, maybe it will be used in the future (I suppose) but for now try to keep the code clean.

Try to refactor the PR and let me know when it works, I'll review again and I'll give you more feedback.

**Comment by sebas095** [comment]
the json folder was only for to do testing,  but  I later fix it (when I get home)

**Comment by leiverandres** [comment]
- We are gonna remove those files, add fix the code style

- The css is still very young, I don't know the right way neither

- Q: I was working in a component to render the list of problems, and @caal-15 has made a component called problem_list. does it do the same thing plus allows to add them to a contest?

**Comment by sebas095** [comment]
@leiverandres Tomorrow do we fix everything?

**Comment by caal-15** [comment]
The main point of using pure css is to style the classes you create in React, so you can style them directly from the css:

    var myClass = React.createClass({
      render: function (){
        return (
          <div className="myClass">
            ...
          </div>
        );
      }
    });

Note that the only property given is a custom className, and then on the CSS

    .myClass {
      padding: 15px;
      ...
    }

And for a specific component inside the class

    .myClass table {
      color: blue;
      ...
    }

Note also that we are using React.createClass(), this is due to a discussion with @pin3da regarding the support for ES6 and the other syntax, please use the React.createClass() syntax in the future.

**Comment by caal-15** [comment]
@leiverandres The developed component for listing problems was created with the purpose of adding problems to a contest in mind, however it also serves as a component to list all the problems, I would suggest you look at the component I created and modify it if you think something is missing, rather than using your own.

**Comment by leiverandres** [comment]
Perfect. I'll keep that un mind

**Comment by caal-15** [comment]
Oh, i forgot something, if you want to use the grid, use it on the html component you are going to render your component into, for example you want your component to be in a row and be 4 columns wide:

On the view.ejs

    <% include header %>
      <div class="row">
        <div class="col-4" id="container">
        </div>
      </div>

On the main.js

    ReactDOM.render(
      <myClass />,
      document.getElementById('container')
    );

**Comment by leiverandres** [comment]
@pin3da @caal-15  guys We think its ok to merge ...
We did:
- a little refactor of requires and deletion of files (json file) don't needed
- ES6 to ES5
- routes of users changed
- Update nav bar

Coming:
- Style improve
- problems.js(improve of carlos's component)

If something missed please tell us :smile:

**Comment by sebas095** [comment]
@aerendon What ideas do you have for improving the style?

**Comment by pin3da** [comment]
I reviewed the patch, some observations:

- The links in the nav var doesn't work. They don't redirect the page in any way.
- If I click the "register" tab more tan once that leads me to a 404 error.
- Please use the port 8081 as default port.
- The page always asks by "fonts/fontawesome-webfont.woff?v=4.4.0" and it doesn't exist.
- In the upper right corner there is a broken link (apparently an icon).

I would merge if you want, but in my opinion we need to stabilize all that work before.

**Comment by sebas095** [comment]
I'll organize some things carlos told me

**Comment by sebas095** [comment]
@pin3da and @caal-15 check it

**Comment by pin3da** [comment]
It seems to work now, two things before merge.

- Why are you re-parsing the answers from the server ? you can use res.boy (which is a json) instead of parse res.text.
- Please squash the commits or something like that in order to keep the git history clear.

Great work ! :+1:

**Comment by pin3da** [comment]
@sebas095 @leiverandres @aerendon @caal-15 Merged... Thanks :tada: :confetti_ball:

**Pull request merged**
